# Generated by Django 6.0 on 2025-12-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_remove_enrollment_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
