# Generated by Django 6.0 on 2025-12-28 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_duration_seconds'),
        ('enrollments', '0006_rename_completed_enrollment_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='enrollments_course__f8877c_idx'),
        ),
    ]
