# Generated by Django 6.0 on 2026-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_enrollment_enrollments_course__f8877c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
