# Generated by Django 6.0 on 2026-01-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventattendancelog_eventfeedback_eventresource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminder_hours_before',
        ),
        migrations.RemoveField(
            model_name='event',
            name='send_reminder',
        ),
    ]
