# Generated by Django 6.0 on 2026-01-02 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_rename_recourse_type_lessonresource_resource_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='student_boo_user_id_1b1370_idx')],
                'unique_together': {('user', 'course'), ('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.IntegerField(default=0, help_text='Video timestamp in seconds where note was taken')),
                ('is_pinned', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='student_not_user_id_0515f3_idx'), models.Index(fields=['user', '-created_at'], name='student_not_user_id_cf50a9_idx'), models.Index(fields=['is_pinned', '-created_at'], name='student_not_is_pinn_aea1d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], max_length=20, null=True)),
                ('learning_goals', models.TextField(blank=True, help_text="Student's learning objectives")),
                ('interests', models.JSONField(default=list, help_text='List of interest tags')),
                ('weekly_study_hours', models.IntegerField(default=0, help_text='Target study hours per week')),
                ('preferred_study_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('total_courses_enrolled', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_certificates_earned', models.IntegerField(default=0)),
                ('total_watch_time', models.IntegerField(default=0, help_text='Total watch time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='student_pro_user_id_f42457_idx'), models.Index(fields=['-created_at'], name='student_pro_created_2df548_idx')],
            },
        ),
    ]
