# Generated by Django 6.0 on 2026-01-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='weekly_digest',
        ),
    ]
