# Generated by Django 6.0 on 2026-01-02 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('criteria', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True / False')], default='mcq', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'user')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['completed_at'], name='assessments_complet_38f25f_idx'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='assessments.assignment'),
        ),
    ]
