# Generated by Django 6.0 on 2026-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
