# Generated by Django 6.0 on 2026-01-03 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('courses', '0010_rename_recourse_type_lessonresource_resource_type_and_more'),
        ('events', '0002_eventattendancelog_eventfeedback_eventresource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('new_enrollments', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registrations', models.PositiveIntegerField(default=0)),
                ('total_attendees', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Event Analytics',
            },
        ),
        migrations.CreateModel(
            name='InstructorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Instructor Analytics',
            },
        ),
        migrations.CreateModel(
            name='LessonAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('average_watch_time', models.PositiveIntegerField(default=0)),
                ('drop_off_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lesson Analytics',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseanalyticssnapshot',
            options={'ordering': ['-snapshot_date']},
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='event_type',
        ),
        migrations.AddField(
            model_name='courseanalyticssnapshot',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='courseanalyticssnapshot',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='events.event'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseanalyticssnapshot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='action',
            field=models.CharField(choices=[('view_course', 'View Course'), ('enroll_course', 'Enroll in Course'), ('complete_lesson', 'Complete Lesson'), ('start_lesson', 'Start Lesson'), ('submit_quiz', 'Submit Quiz'), ('post_review', 'Post Review'), ('bookmark_course', 'Bookmark Course'), ('search', 'Search'), ('view_event', 'View Event'), ('register_event', 'Register for Event'), ('join_circle', 'Join Learning Circle'), ('create_post', 'Create Forum Post'), ('like_post', 'Like Post')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseanalyticssnapshot',
            index=models.Index(fields=['course', '-snapshot_date'], name='analytics_c_course__fd6051_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_dd114e_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['action', '-created_at'], name='analytics_u_action_c4e872_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['course', '-created_at'], name='analytics_u_course__2cba61_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplatformmetrics',
            index=models.Index(fields=['-date'], name='analytics_d_date_bf6c42_idx'),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='instructor',
            field=models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonanalytics',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['-created_at'], name='analytics_s_created_5d0a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['query'], name='analytics_s_query_44edad_idx'),
        ),
    ]
