# Generated by Django 6.0 on 2026-01-04 05:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Final course grade percentage', max_digits=5, null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when course was completed', null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', 'course'], name='certificate_user_id_2a7ce8_idx'), models.Index(fields=['verification_code'], name='certificate_verific_e033f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_certificate_per_user_course')],
            },
        ),
    ]
