# Generated by Django 6.0 on 2026-01-02 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_unique_together_and_more'),
        ('courses', '0010_rename_recourse_type_lessonresource_resource_type_and_more'),
        ('enrollments', '0008_lessonprogress_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='completion_date',
            field=models.DateTimeField(blank=True, help_text='Date when course was completed', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final course grade percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'course'], name='certificate_user_id_2a7ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='certificate_verific_e033f7_idx'),
        ),
    ]
