# Generated by Django 6.0 on 2026-01-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_wallet_to_profile'),
        ('accounts', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
    ]
