# Generated by Django 6.0 on 2026-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, help_text='User wallet balance', max_digits=12),
        ),
    ]
