# Generated by Django 6.0 on 2026-01-03 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_rename_recourse_type_lessonresource_resource_type_and_more'),
        ('live', '0002_alter_eventregistration_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('class', 'Live Class'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('qa', 'Q&A Session'), ('office_hours', 'Office Hours')], default='class', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('timezone_info', models.CharField(default='UTC', max_length=50)),
                ('platform', models.CharField(choices=[('agora', 'Agora'), ('zoom', 'Zoom'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('custom', 'Custom Platform')], default='agora', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=255)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('stream_key', models.CharField(blank=True, max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('app_id', models.CharField(blank=True, max_length=255)),
                ('max_participants', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_qa', models.BooleanField(default=True)),
                ('enable_polls', models.BooleanField(default=True)),
                ('enable_recording', models.BooleanField(default=True)),
                ('enable_screen_share', models.BooleanField(default=True)),
                ('requires_enrollment', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live Now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_questions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='live.livesession')),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('allow_multiple_answers', models.BooleanField(default=False)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='live.livesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('file', 'File'), ('system', 'System')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('file_url', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='live.livechatmessage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.livesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('votes_count', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='live.livepoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='live.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='live.livepoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('joined', 'Joined'), ('left', 'Left'), ('banned', 'Banned')], default='registered', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('polls_answered', models.IntegerField(default=0)),
                ('can_unmute', models.BooleanField(default=False)),
                ('can_share_screen', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_present', models.BooleanField(default=False)),
                ('attendance_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='live.livesession')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='live.sessionparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('requires_enrollment', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='live.livesession')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_duration_seconds', models.IntegerField(default=0)),
                ('last_position_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='live.sessionrecording')),
            ],
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course', 'status'], name='live_livese_course__1ce3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['instructor'], name='live_livese_instruc_bbeebd_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['scheduled_start'], name='live_livese_schedul_3ae396_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='live_livese_status_3df47e_idx'),
        ),
        migrations.AddIndex(
            model_name='livequestion',
            index=models.Index(fields=['session', 'status'], name='live_livequ_session_bb068e_idx'),
        ),
        migrations.AddIndex(
            model_name='livequestion',
            index=models.Index(fields=['user'], name='live_livequ_user_id_9961d4_idx'),
        ),
        migrations.AddIndex(
            model_name='livequestion',
            index=models.Index(fields=['-upvotes'], name='live_livequ_upvotes_98527e_idx'),
        ),
        migrations.AddIndex(
            model_name='livepoll',
            index=models.Index(fields=['session', 'status'], name='live_livepo_session_42071d_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['session', 'created_at'], name='live_livech_session_469470_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['user'], name='live_livech_user_id_6890f6_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['is_pinned'], name='live_livech_is_pinn_3944e7_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'order'], name='live_pollop_poll_id_336315_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'user'], name='live_pollvo_poll_id_15065f_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option'], name='live_pollvo_option__b6a287_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'status'], name='live_sessio_session_748b48_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['user'], name='live_sessio_user_id_b93449_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session'], name='live_sessio_session_973b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['marked_present'], name='live_sessio_marked__a26439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'participant')},
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['session'], name='live_sessio_session_13d7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['processing_status'], name='live_sessio_process_80d2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingview',
            index=models.Index(fields=['recording'], name='live_record_recordi_d3247d_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingview',
            index=models.Index(fields=['user'], name='live_record_user_id_cb68e6_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingview',
            index=models.Index(fields=['completed'], name='live_record_complet_039670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingview',
            unique_together={('recording', 'user')},
        ),
    ]
