# Generated by Django 6.0 on 2026-01-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='send_reminder',
        ),
    ]
