# Generated by Django 6.0 on 2026-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
