# Generated by Django 6.0 on 2025-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_durattion',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
            preserve_default=False,
        ),
    ]
