# Generated by Django 6.0 on 2026-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_rejection_reason_course_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonresource',
            old_name='recourse_type',
            new_name='resource_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_durattion',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
    ]
