# Generated by Django 6.0 on 2026-01-02 18:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_rename_recourse_type_lessonresource_resource_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_enrollment', 'New Enrollment'), ('new_review', 'New Review'), ('question', 'New Question'), ('payout', 'Payout Update'), ('course_published', 'Course Published'), ('course_flagged', 'Course Flagged')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_notifications', to='courses.course')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_instructor_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', '-created_at'], name='instructor__instruc_35cf66_idx'), models.Index(fields=['is_read'], name='instructor__is_read_478bd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstructorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('payment_details', models.JSONField(default=dict, help_text='Payment method details')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_payouts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', '-created_at'], name='instructor__instruc_76de8b_idx'), models.Index(fields=['status'], name='instructor__status_1614e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, help_text='Instructor biography')),
                ('headline', models.CharField(blank=True, help_text='Professional headline', max_length=255)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('expertise_areas', models.JSONField(default=list, help_text='List of expertise areas')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('education', models.JSONField(default=list, help_text='Educational background')),
                ('total_courses', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='instructor__user_id_31420a_idx'), models.Index(fields=['is_verified'], name='instructor__is_veri_05238c_idx'), models.Index(fields=['-average_rating'], name='instructor__average_5aaa7a_idx'), models.Index(fields=['-total_students'], name='instructor__total_s_9726dd_idx')],
            },
        ),
    ]
