# Generated by Django 6.0 on 2026-01-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instructornotification',
            name='instructor__instruc_35cf66_idx',
        ),
        migrations.RemoveIndex(
            model_name='instructornotification',
            name='instructor__is_read_478bd6_idx',
        ),
        migrations.DeleteModel(
            name='InstructorNotification',
        ),
    ]
