# Generated by Django 6.0 on 2025-12-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('push', 'Push Notification')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='allow_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
