# Generated by Django 6.0 on 2026-01-04 05:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('estimated_weeks', models.IntegerField(default=0)),
                ('is_official', models.BooleanField(default=False, help_text='Curated by platform')),
                ('is_published', models.BooleanField(default=False)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('completion_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_official', '-enrollment_count'],
            },
        ),
        migrations.CreateModel(
            name='PathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='ai_recommender.learningpath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='courses',
            field=models.ManyToManyField(related_name='learning_paths', through='ai_recommender.PathCourse', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('creative', 'Creative'), ('business', 'Business'), ('language', 'Language'), ('personal', 'Personal Development'), ('science', 'Science & Math'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('popularity_score', models.FloatField(default=0.0, help_text='Calculated based on course enrollments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['category', '-popularity_score'], name='ai_recommen_categor_e19e2e_idx'), models.Index(fields=['is_active', '-popularity_score'], name='ai_recommen_is_acti_e7abd4_idx')],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='required_skills',
            field=models.ManyToManyField(related_name='learning_paths', to='ai_recommender.skill'),
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Importance of this skill in the course (1.0 = primary, 0.5 = secondary)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('is_primary', models.BooleanField(default=False, help_text='Is this a primary learning outcome?')),
                ('added_by', models.CharField(choices=[('instructor', 'Instructor'), ('admin', 'Admin'), ('ai', 'AI Detected')], default='instructor', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='courses.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='ai_recommender.skill')),
            ],
            options={
                'ordering': ['-weight', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(help_text='Target job title or career goal', max_length=200)),
                ('gap_score', models.FloatField(default=0.0, help_text='Overall skill gap (0 = no gap, 100 = complete gap)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('priority_skills', models.JSONField(default=list, help_text='List of skills to focus on first')),
                ('estimated_learning_hours', models.IntegerField(default=0, help_text='Estimated time to close gap')),
                ('is_active', models.BooleanField(default=True)),
                ('progress', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_skills', models.ManyToManyField(related_name='required_for_roles', to='ai_recommender.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Gap Analysis',
                'verbose_name_plural': 'Skill Gap Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('completion_count', models.IntegerField(default=0)),
                ('trend_score', models.FloatField(default=0.0, help_text='Calculated trend score based on growth rate')),
                ('rank', models.IntegerField(default=0, help_text='Ranking in trending list')),
                ('rank_change', models.IntegerField(default=0, help_text='Change from previous period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_data', to='ai_recommender.skill')),
            ],
            options={
                'ordering': ['-period_end', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.FloatField(default=1.0, help_text='How interested is the user? (1.0 = normal, 5.0 = very interested)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('reason', models.CharField(choices=[('learning_goal', 'Learning Goal'), ('career_change', 'Career Change'), ('hobby', 'Hobby/Personal Interest'), ('job_requirement', 'Job Requirement'), ('recommendation', 'Recommended')], default='learning_goal', max_length=50)),
                ('target_proficiency', models.FloatField(default=50.0, help_text='Desired proficiency level', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('deadline', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='ai_recommender.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interest_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='path_completions', to='courses.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='ai_recommender.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.FloatField(default=0.0, help_text='Skill level: 0-100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('source', models.CharField(choices=[('course', 'Course Completion'), ('manual', 'Self-Reported'), ('assessment', 'Assessment Result'), ('imported', 'Imported Profile')], default='course', max_length=50)),
                ('first_learned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_practiced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='ai_recommender.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proficiency', '-last_practiced_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Recommendation confidence score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('algorithm', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('hybrid', 'Hybrid'), ('skill_gap', 'Skill Gap Analysis'), ('trending', 'Trending'), ('similar_users', 'Similar Users')], max_length=50)),
                ('reason', models.TextField(help_text='Why this course was recommended')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('enrolled', 'Enrolled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional algorithm-specific data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When recommendation becomes stale', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('matched_skills', models.ManyToManyField(blank=True, related_name='recommendations', to='ai_recommender.skill')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-score'], name='ai_recommen_user_id_a3cc24_idx'), models.Index(fields=['user', '-created_at'], name='ai_recommen_user_id_041490_idx'), models.Index(fields=['algorithm', '-score'], name='ai_recommen_algorit_186b61_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', '-enrollment_count'], name='ai_recommen_is_publ_e29d38_idx'),
        ),
        migrations.AddIndex(
            model_name='courseskill',
            index=models.Index(fields=['course', '-weight'], name='ai_recommen_course__eabf47_idx'),
        ),
        migrations.AddIndex(
            model_name='courseskill',
            index=models.Index(fields=['skill', '-weight'], name='ai_recommen_skill_i_b6511c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skillgapanalysis',
            index=models.Index(fields=['user', 'is_active'], name='ai_recommen_user_id_35d2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingskill',
            index=models.Index(fields=['-period_end', 'rank'], name='ai_recommen_period__d2b03b_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingskill',
            index=models.Index(fields=['skill', '-period_end'], name='ai_recommen_skill_i_fdaf6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendingskill',
            unique_together={('skill', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-interest_level'], name='ai_recommen_user_id_af844c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='userlearningpath',
            unique_together={('user', 'learning_path')},
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', '-proficiency'], name='ai_recommen_user_id_cbee00_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill', '-proficiency'], name='ai_recommen_skill_i_b80c50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
